### ISSUE TITLE
Error: the requested accessory Sonoff was not registered by any plugin

### ISSUE THREAD

**Issue by marcotini** [suculent/homebridge-plugin-sonoff#1]
When I start Homebridge this message show to me:

```
/usr/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Sonoff' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Why? What I did wrong?

**Comment by suculent** [comment]
It seems you have added the accessory section to ~/.homebridge/config.json but not installed the plugin beforehands.

cd to its directory and in Terminal, do "npm install ." in order to install the plugin and thm restart the homebridge.

You should be good to go.

Matej

**Comment by marcotini** [comment]
In which directory I need to install it? Because I try in ~/.homebridge/ but it's not working...

**Comment by suculent** [comment]
From the directory you have checked out from GitHub. 



Odesláno z iPhonu

26. 1. 2017 v 19:25, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
Like where? My directory is ~/.homebridge/ but all other plugin that I've installed, I installed them doing: npm install nameplugin.

**Comment by suculent** [comment]
But when doing the npm install nameplugin you're installing from npm repo, not locally i guess. 

By npm install . you install from sources in current folder. 

Odesláno z iPhonu

30. 1. 2017 v 15:33, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
Ok but how can I install this repo? If I clone and then install, it doesn't work.

**Comment by suculent** [comment]
After doing:

git clone https://github...
cd homebridge-plugin-sonoff
npm install -g .

What happens? This is how I do it on 3 different machines. There is no nom package published yet. 

Odesláno z iPhonu

30. 1. 2017 v 19:07, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
```
[1/31/2017, 11:19:24 AM] [Sonoff Switch] Initializing Sonoff accessory...
[1/31/2017, 11:19:24 AM] [Sonoff Switch] Config is missing mqtt_channel, fallback to default.
Connecting to mqtt broker: 192.168.1.105
/usr/lib/node_modules/homebridge-sonoff/node_modules/mqtt/lib/connect/index.js:54
      throw new Error('Missing protocol')

```

**Comment by suculent** [comment]
Aha, this is my bug in the config sample. Add 'mqtt://' before your IP address to solve this. 

Odesláno z iPhonu

31. 1. 2017 v 12:22, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
Ok now it's start but it's not work.

```
[1/31/2017, 11:29:16 AM] [Sonoff Switch] getPowerState callback(null, undefined)
[1/31/2017, 11:29:21 AM] [Sonoff Switch] setPowerState: 1
[1/31/2017, 11:29:25 AM] [Sonoff Switch] setPowerState: 0
```

There are no other dependence? I already install _mosquito_, but I didn't configure it.

**Comment by marcotini** [comment]
Or maybe I need to configure the share inside the app?

**Comment by suculent** [comment]
There is no additional setup required to default mosquitto installation. 

It seems to work. What about your Sonoff log?

Odesláno z iPhonu

31. 1. 2017 v 12:31, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
```
[1/31/2017, 11:41:41 AM] [Sonoff Switch] Initializing Sonoff accessory...
[1/31/2017, 11:41:41 AM] [Sonoff Switch] Config is missing mqtt_channel, fallback to default.
Connecting to mqtt broker: mqtt://192.168.1.105
```

And then:

```
MQTT connected, subscribing to: /sonoff
no did or loc found!
```

**Comment by suculent** [comment]
Check the json config for trailing spaces before "
> no did or loc found!

This is not message from this plugin. 


Odesláno z iPhonu

31. 1. 2017 v 12:47, Marco Tini <notifications@github.com>:

**Comment by marcotini** [comment]
Now it's tell me that it can connect:

```
[1/31/2017, 2:03:37 PM] [Sonoff Switch] Initializing Sonoff accessory...
Connecting to mqtt broker: mqtt://192.168.1.105
```

```
MQTT connected, subscribing to: /sonoff
connect ok!
```

But when I click inside the Home app:
```
[1/31/2017, 2:03:53 PM] [Sonoff Switch] getPowerState callback(null, undefined)
[1/31/2017, 2:04:00 PM] [Sonoff Switch] setPowerState: 1
[1/31/2017, 2:04:01 PM] [Sonoff Switch] setPowerState: 0
[1/31/2017, 2:04:05 PM] [Sonoff Switch] setPowerState: 1
```
And then nothing happen... are you sure we are talking about the same Sonoff? I have [this one](https://cdn.itead.cc/media/catalog/product/cache/1/thumbnail/160x160/9df78eab33525d08d6e5fb8d27136e95/s/o/sonoff_03.jpg).

**Comment by suculent** [comment]
Well, from now on you need to debug on the Sonoff side. Is it connecting to your WiFi and MQTT as well?

• It needs to have its firmware replaced with the one in esp8266 folder (Sonoff has 4 positions on the PCB where you solder pins for USB-FTDI interface). There’s tutorial I’ve successfully used to do that: http://captain-slow.dk/2016/05/22/replacing-the-itead-sonoff-firmware/

• Pull latest version from the GitHub, I’ve made some changes there to make it easier for you.

• Edit the esp8266/config.lua then upload all 3 files to the Sonoff (I’m doing it using ESPlorer). init.lua will start the sonoff.lua after 3 seconds while reading configuration from config.lua.

**Comment by marcotini** [comment]
Sorry but there are not other way to use MQTT without change the firmware? Maybe with something like Domoticz? It's because I don't want to solder pins or connectors.

**Comment by suculent** [comment]
All you need is soldering gun, socket for 0,1 EUR and FTDI-USB convertor for 4 EUR byt that's a IoT must-have anyway :o)


Odesláno z iPhonu

15. 2. 2017 v 9:59, Marco Tini <notifications@github.com>:

**Comment by pirasmos** [comment]
Hello. I have a question. I load the firmware with the ESP8266Flasher.exe. Next i load the init.lua and the config.lua files with ESPlorer. I ping the device but every 10sec it restarts... What I doing wrong? I must change anything on the file init.lua? Thanks

**Comment by suculent** [comment]
You should edit the config before uploading to match your ssid, password, mqtt broker address and possibly adjust a channel. 

Firmware has no special requirements, you can go with vanilla nodemcu. 

Odesláno z iPhonu

28. 2. 2017 v 10:46, pirasmos <notifications@github.com>:

**Comment by pirasmos** [comment]
Ok . I have connection with the sonoff with my ssid , password and a IP
adress,  but it restarts every 10sec...

2017-02-28 14:34 GMT+02:00 Matej Sychra <notifications@github.com>:

**Comment by suculent** [comment]
That’s really weird. I’ve used current code-base less than two weeks ago to install one.

What kind of firmware are you using?

**Comment by pirasmos** [comment]
I install the Firmware with ESP8266Flasher.exe NODEMCU. I notice when i
change in the file init.lue on line 49 ,tmr.alarm(1, 10000, 0, function().
change from 10000 to 100000
it restarts after a minute



2017-02-28 17:18 GMT+02:00 Matej Sychra <notifications@github.com>:

> That’s really weird. I’ve used current code-base less than two weeks ago
> to install one.
>
> What kind of firmware are you using?
>
>

**Comment by suculent** [comment]
OK, what the code is supposed to do, is that it defines an ‘offline’ handler that is called after MQTT gets disconnected and last will that should appear in your MQTT channel when the broker finds out device has disconnected (but only after it has been successfully connected to transmit the ‘last will and testament').

When this happens (e.g. WiFi is down due to power outage), device reboots after 10 seconds in order to retry, until successfully connected. Device stops rebooting when all of the SSID/password/MQTT setup is correct.

What’s happening in your case is that the device app actually does not connect (or gets disconnected) to/from your MQTT broker IP and that’s why it decides to reboot.

Do you have any authentication on your MQTT broker? You should then adjust the mqtt_user and mqtt_pass parameters in configuration (recently renamed from mqttUser and mqttPass due to the code style).

Let me know how it goes.

Cheers,
Matej

**Comment by marcotini** [comment]
> All you need is soldering gun, socket for 0,1 EUR and FTDI-USB convertor for 4 EUR byt that's a IoT must-have anyway :o)

Yeah sorry, I'm just waiting for it (the FTDI) arrives.

**Comment by cultos** [comment]
Hello !
Sorry for maybe stupied question, but cant understand:
Afrer install homebridge / plugin mqtt-switch I need to install Mosquito or not ?
Or Edit config and sonoff device and thats all ?

**Comment by suculent** [comment]
Hello,

the plugin expects you have MQTT broker running somewhere. 

However the error you’ve mentioned seems more like the plugin is not installed with ´npm -g .´ or there is no configuration in config.json

Odesláno z iPhonu

7. 4. 2018 v 21:37, cultos <notifications@github.com>:
